# YOUR NAME OR TITLE OF YOUR SITE
name: Indranil Dutta

# YOUR BRAND/PERSONAL TAGLINE
tagline: Hello, I'm Indranil Dutta. I'm from Kolkata, the city of joy ❤️. I'm a frotend developer who works on both mobile and web. I'm the lead organiser of GDG Kolkata and I also love to photograph beautiful memories 

# YOUR/BRAND IMAGE URL
Image_URL: https://lh3.googleusercontent.com/a-/AFdZucpe7oQcOdxT9ZsWMFds7kBKTr43Bbtg8jwM5jr4IA=s810-p-rw-no

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://picsum.photos/1080?nocache=

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    # FACEBOOK
  - Name: Facebook
    URL: https://www.facebook.com
    Username: indranildutta.6
    Color: '#3b5998'
    Icon-Class: fab fa-facebook

    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: iamindranildutta
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram

    # TWITTER
  - Name: Twitter
    URL: https://twitter.com
    Username: indranildutta06
    Color: '#1DA1F2'
    Icon-Class: fab fa-twitter

     # THREADS.NET
  - Name: Threads
    URL: https://threads.net/
    Username: iamindranildutta
    Color: '#000000'
    Icon-Class: fa-solid fa-at
    Text_Color: '#ffffff'
    
    # LINKEDIN
  - Name: LinkedIn
    URL: https://www.linkedin.com/in
    Username: indranil-dutta-06
    Color: '#2867B2'
    Icon-Class: fab fa-linkedin-in

    # YOUTUBE
  - Name: YouTube
    URL: https://www.youtube.com/@
    Username: DishaAndNil
    Color: '#ff0000'
    Icon-Class: fab fa-youtube

    # GITHUB
  - Name: GitHub
    URL: http://github.com
    Username: indranildutta06
    Color: '#6e5494'
    Icon-Class: fab fa-github

    # EMAIL
  - Name: Email
    URL: 'mailto:neeldutta.93@gmail.com'
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#ffffff'

    
    # MESSENGER
  - Name: Messenger
    URL: https://m.me
    Username: indranildutta.6
    Color: '#006AFF'
    Icon-Class: fab fa-facebook-messenger


  #   # WHATSAPP
  # - Name: WhatsApp
  #   URL: https://wa.me
  #   Username: '+1123456789'
  #   Color: '#25d366'
  #   Icon-Class: fab fa-whatsapp

    # TELEGRAM
  - Name: Telegram
    URL: http://telegram.me
    Username: indranildutta
    Color: '#0088cc'
    Icon-Class: fab fa-telegram-plane

    
  #   # DISCORD
  # - Name: Discord
  #   URL: 'https://discord.gg'
  #   Username: 
  #   Icon-Class: fab fa-discord
  #   Color: '#5865F2'
  #   Text_Color: '#ffffff'

   
  #   # DRIBBBLE
  # - Name: Dribbble
  #   URL: https://dribbble.com
  #   Username: 
  #   Color: '#ea4c89'
  #   Icon-Class: fab fa-dribbble

    
    
  #    # TIKTOK
  # - Name: TikTok
  #   URL: https://www.tiktok.com
  #   Username: 
  #   Color: '#FE2C55'
  #   Icon-Class: fab fa-tiktok

    # MEDIUM
  - Name: Medium
    URL: 'https://medium.com'
    Username: '@indranildutta.6'
    Icon-Class: fab fa-medium-m
    Color: '#00ab6c'
    Text_Color: '#ffffff'

    
  #   # TUMBLR
  # - Name: Tumblr
  #   URL: https://www.tumblr.com
  #   Username: 
  #   Color: '#35465c'
  #   Icon-Class: fab fa-tumblr

 

    
  - Name: Links
    URL: https://github.com/indranildutta06/indranil_links
    Icon-Class: fas fa-link
    Color: '#d94869'
    Text_Color: '#ffffff'

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: ''

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
